version: "3.4"

####################
#### EXTENSIONS ####
####################
x-default-logging: &default-logging
  logging:
    options:
      max-size: "1G"
      max-file: "3"
    driver: json-file

x-network-default: &network-default
  networks:
    - default

x-common-variables: &common-variables
  docker: "true"

volumes:
  node_modules:

####################
#### SERVICES ######
####################
services:

  ### TGCC-API  ########################################
  tgcc-api:
    container_name: tgcc-api
    image: jslmariano/tgcc-api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - "7308:80"
    environment:
      <<: *common-variables
    <<: [*default-logging, *network-default]

  ### TGCC-web  ########################################
  tgcc-web:
    container_name: tgcc-web
    image: jslmariano/tgcc-web
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "7309:80"
    environment:
      <<: *common-variables
    <<: [*default-logging, *network-default]
